### ISSUE TITLE
Read huge file in chunks

### ISSUE THREAD

**Issue by mhavey** [brightsparklabs/asanti#104]
I'm looking for a code pattern to decode a huge BER input file consisting of thousands/millions of call records. I don't want to obtain a huge immutable list of call record PDU's in one shot. Rather, I want to obtain a list of decoded PDU's in smaller chunks, say 100 at a time. 

Can you recommend a good code pattern for this?

I am trying the following, but I'm noticing it always gives me the first 100 PDUs. My intention is to get the first 100, the next 100, and so on. I'm expecting my Ber source to work like a stream, where you process from the current position, rather than from the start of the file each time:

	public static final int CHUNK_SIZE = 100;
		String schemaFileName = "xyz.asn";
		String inputFileName = "abc.ber";
		ByteSource berSource = Files.asByteSource(new File(inputFileName));
		CharSource schemaSource = Files.asCharSource(new File(schemaFileName), Charsets.UTF_8);
		AsnSchema schema = AsnSchemaReader.read(schemaSource);

			while (true /* really want to stop when EOF */ ) { 
				ImmutableList<RawAsnData> allRawAsnData = Asanti.readAsnBerData(berSource, CHUNK_SIZE);
				for (int i = 0; i < allRawAsnData.size(); i++) {
					AsantiAsnData asnData = Asanti.decodeAsnData(allRawAsnData.get(i), schema, "CallEventRecord");
					//process the data
				}
			}
	}

**Comment by al-jeyapal** [comment]
Hi @mhavey,

Unfortunately there isn't native support for streaming at the moment. It's not a use case we've needed to handle thus far. Certainly can see why it's useful.

Two options:
- either do some pre-processing to split up the BER file prior to feeding it into Asanti
- raise a PR for a `AsnSchemaStreamingReader`
