### ISSUE TITLE
Add dependabot to keep dependencies fresh

### ISSUE THREAD

**Issue by al-jeyapal** [brightsparklabs/asanti#105]
See https://dependabot.com/

**Comment by glen-wiltshire-bsl** [comment]
There is currently two versions of dependabot, the older application that integrates with github that is run and managed from the dependabot website and the newer github native version.
The native version is currently in beta but with how nicely it integrates (and how it does not clean up anything created by the older version after upgrading) I would recommend going with the native version. 

To enable dependabot on a github repo add a yml file that defines the configuration under `<root of repo>/.github/dependabot.yml` for configuration options see [Configuration options for dependency updates](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates)

To see the dependabot UI, after the config file is added to the repo:
1. Navigate to the github page for the repo.
2. Select the `Insights` tab
3. Select the `Dependency graph` menu item on the left
4. Select the `dependabot` tab
If the tab is not present either the config file is not present, or is invalid. Looking at the config file in the PR/commit it was added under in github will show if it is invalid. Alternatively you can validate your config [here](https://dependabot.com/docs/config-file/validator/)

To manually trigger a dependency check:
1. Nagivate to the dependabot UI
2. Select the `Last checked xxx ago` link
3. Select the `Check for updates` button


notes:
- Dependabot will create a separate PR for each dependency update it finds.
- Each PR contains Release notes, changelogs, commit links, vulnerability details.
- Can be configured to run on any schedule (daily, weekly etc). Weekly will default to Monday 5AM UTC.
- Java gradle support is still in beta but for the most part produces better output than our existing dependency checking task. I still had to use the existing gradlew task to see that gradlew needed to be updated.
- If a dependency is updated outside of the created PR dependabot will close the PR on next run.
