### ISSUE TITLE
getBuiltinType() returns SequenceOf for a element inside SEQUENCE OF primivite

### ISSUE THREAD

**Issue by sflanaga** [brightsparklabs/asanti#119]
I've run into an issue, while seeing how to work with asanti data model, using 2.1.  The concern is around handling types in a "SEQUENCE OF <primitive>".

The tag list returns a /x/y/z[0] and the value is just a string, but the return type is of SequenceOf from 

I can pull the data at /x/y/z manually, and it's type is SequenceOf.

However, when I get /x/y/z[0] it is also SequenceOf instead of the primitive type.

The data I testing with is CDR data and cannot post details here.

BTW: I really like the fundamental idea of getting rid of concrete classes.

**Comment by al-jeyapal** [comment]
Hey mate, it's a little tricky to debug that.
Could you mock up a schema and some data to reproduce so we can replicate?
